---

# Cek migrasi rilis symlink
- stat:
    path: "{{ sebar_deploy_to }}/{{ sebar_current_dir }}"
  register: stat_current_dir

- name: SEBAR | Hapus folder saat ini jika symlink
  file:
    state: absent
    path: "{{ sebar_deploy_to }}/{{ sebar_current_dir }}"
  when: stat_current_dir.stat.islnk is defined and stat_current_dir.stat.islnk

# Melakukan tugas rsync
- name: SEBAR | Memastikan folder saat ini adalah directory
  file:
    state: directory
    path: "{{ sebar_deploy_to }}/{{ sebar_current_dir }}"

- name: SEBAR | Sync release to new current path
  command: rsync -a -F --no-times --delete-after "{{ sebar_release_path.stdout }}/" "{{ sebar_deploy_to }}/{{ sebar_current_dir }}/"

# Memastikan symlink tidak ada
- name: SEBAR | Memastikan folder shared belum terbuat
  file:
    state: absent
    path: "{{ sebar_deploy_to }}/{{ sebar_current_dir }}/{{ item }}"
  with_flattened:
    - "{{ sebar_shared_paths }}"
    - "{{ sebar_shared_files }}"

# Symlinks shared paths
- name: SEBAR | Membuat softlink untuk path saat ini
  file:
    state: link
    path: "{{ sebar_deploy_to }}/{{ sebar_current_dir }}/{{ item }}"
    src: "{{ item | regex_replace('[^\\/]*', '..') }}/shared/{{ item }}"
  with_flattened:
    - "{{ sebar_shared_paths }}"
    - "{{ sebar_shared_files }}"
