---
# Setup folders
- name: SEBAR | Ensure deployment base path exists
  file:
    state: directory
    path: "{{ sebar_deploy_to }}"

- name: SEBAR | Ensure releases folder exists
  file:
    state: directory
    path: "{{ sebar_releases_path }}"

- name: SEBAR | Ensure shared elements folder exists
  file:
    state: directory
    path: "{{ sebar_shared_path }}"

# Ensure shared path exists
- name: SEBAR | Ensure shared paths exists
  file:
    state: directory
    path: "{{ sebar_shared_path }}/{{ item }}"
  with_items: "{{ sebar_shared_paths }}"
  when: sebar_ensure_shared_paths_exist

# Ensure basedir shared files exists
- name: SEBAR | Ensure basedir shared files exists
  file:
    state: directory
    path: "{{ sebar_shared_path }}/{{ item | dirname }}"
  with_items: "{{ sebar_shared_files }}"
  when: sebar_ensure_basedirs_shared_files_exist
