---
# Membuat folder
- name: SEBAR | Memastikan path rilis tersedia
  file:
    state: directory
    path: "{{ sebar_deploy_to }}"

- name: SEBAR | Memastikan folder rilis ada
  file:
    state: directory
    path: "{{ sebar_releases_path }}"

- name: SEBAR | Memastikan folder shared element ada
  file:
    state: directory
    path: "{{ sebar_shared_path }}"

# Memastikan path shared tersedia
- name: SEBAR | Memastikan path shared tersedia
  file:
    state: directory
    path: "{{ sebar_shared_path }}/{{ item }}"
  with_items: "{{ sebar_shared_paths }}"
  when: sebar_ensure_shared_paths_exist

# Memastikan basedir file untuk shared ada
- name: SEBAR | Memastikan basedir file untuk shared ada
  file:
    state: directory
    path: "{{ sebar_shared_path }}/{{ item | dirname }}"
  with_items: "{{ sebar_shared_files }}"
  when: sebar_ensure_basedirs_shared_files_exist
