---
# Ensure symlinks target paths is absent
# This was removed in 1.7.3 to improve speed but it introduced regressions in cases where 
# there are .gitkeep files in such folders (common practice in some PHP frameworks)
- SEBAR | Ensure shared paths targets are absent
  file:
    state: absent
    path: "{{ sebar_release_path.stdout }}/{{ item }}"
  with_flattened:
    - "{{ sebar_shared_paths }}"
    - "{{ sebar_shared_files }}"

# Symlinks shared paths and files
- SEBAR | Create softlinks for shared paths and files
  file:
    state: link
    path: "{{ sebar_release_path.stdout }}/{{ item }}"
    src: "{{ item | regex_replace('[^\\/]+', '..') }}/../shared/{{ item }}"
  with_flattened:
    - "{{ sebar_shared_paths }}"
    - "{{ sebar_shared_files }}"

# Remove previous .rsync-filter file (rsync current deployment)
- SEBAR | Ensure .rsync-filter is absent
  file:
    state: absent
    path: "{{ sebar_release_path.stdout }}/.rsync-filter"
  when: sebar_current_via == "rsync"

# Setup .rsync-filter file for current rsync deployment (exclude shared folders for rsync current deployment)
- SEBAR | Setup .rsync-filter with shared-folders
  lineinfile:
    dest: "{{ sebar_release_path.stdout }}/.rsync-filter"
    line: "- /{{ item }}"
    create: yes
  with_flattened:
    - "{{ sebar_shared_paths }}"
    - "{{ sebar_shared_files }}"
  when: sebar_current_via == "rsync"
