---
# Ensure symlinks target paths is absent
- name: SEBAR | Memastikan shared path tujuan tidak ditemukan
  file:
    state: absent
    path: "{{ sebar_release_path.stdout }}/{{ item }}"
  with_flattened:
    - "{{ sebar_shared_paths }}"
    - "{{ sebar_shared_files }}"

# Symlinks shared paths and files
- name: SEBAR | Membuat softlinks untuk path folder shared dan files
  file:
    state: link
    path: "{{ sebar_release_path.stdout }}/{{ item }}"
    src: "{{ item | regex_replace('[^\\/]+', '..') }}/../shared/{{ item }}"
  with_flattened:
    - "{{ sebar_shared_paths }}"
    - "{{ sebar_shared_files }}"

# Remove previous .rsync-filter file (rsync current deployment)
- name: SEBAR | Memastikan .rsync-filter tidak ditemukan
  file:
    state: absent
    path: "{{ sebar_release_path.stdout }}/.rsync-filter"
  when: sebar_current_via == "rsync"

# Setup .rsync-filter file for current rsync deployment (exclude shared folders for rsync current deployment)
- name: SEBAR | Memasang .rsync-filter dengan shared-folders
  lineinfile:
    dest: "{{ sebar_release_path.stdout }}/.rsync-filter"
    line: "- /{{ item }}"
    create: yes
  with_flattened:
    - "{{ sebar_shared_paths }}"
    - "{{ sebar_shared_files }}"
  when: sebar_current_via == "rsync"
