---
# Update code deployment step
- name: SEBAR | Get release version
  set_fact:
    sebar_release_version: "{{ lookup('pipe', 'date -u +%Y%m%d%H%M%SZ') }}"
  run_once: true
  when: sebar_release_version is not defined
  delegate_to: 127.0.0.1

- name: SEBAR | Get release path
  command: echo "{{ sebar_releases_path }}/{{ sebar_release_version }}"
  register: sebar_release_path

- include: "update-code/{{ sebar_deploy_via | default('rsync') }}.yml"

- name: SEBAR | Copy release version into REVISION file
  copy:
    content: "{{ sebar_release_version }}"
    dest: "{{ sebar_release_path.stdout }}/REVISION"
  when: sebar_git_result is not defined

- name: SEBAR | Copy git released version into REVISION file
  copy:
    content: "{{ sebar_git_result.after }}"
    dest: "{{ sebar_release_path.stdout }}/REVISION"
  when: sebar_git_result is defined
