---
- include: copy.yml

- name: sebar | copy_unarchive | Set archived file
  set_fact:
    sebar_archived_file: "{{ sebar_release_path.stdout }}/{{ sebar_deploy_from | basename }}"

- include: unarchive.yml
