---
- name: sebar | SCP | Create release folder
  file:
    state: directory
    path: "{{ sebar_release_path.stdout }}"

- name: sebar | SCP | Deploy existing code to remote servers
  copy:
    src: "{{ sebar_deploy_from }}"
    dest: "{{ sebar_release_path.stdout }}"
