---
- SEBAR | RSYNC | Get shared path (in rsync case)
  command: echo "{{ sebar_shared_path }}/.shared-copy"
  register: sebar_shared_rsync_copy_path

- SEBAR | RSYNC | Rsync application files to remote shared copy
  synchronize:
    src: "{{ sebar_deploy_from }}"
    dest: "{{ sebar_shared_rsync_copy_path.stdout }}"
    set_remote_user: "{{ sebar_rsync_set_remote_user }}"
    recursive: yes
    delete: yes
    archive: yes
    compress: yes
    use_ssh_args: "{{ sebar_rsync_use_ssh_args | default(omit) }}"
    rsync_opts: "{{ sebar_rsync_extra_params | default(omit) }}"
    rsync_path: "{{ sebar_rsync_path | default(omit) }}"

- SEBAR | RSYNC | Deploy existing code to servers
  command: cp -a {{ sebar_shared_rsync_copy_path.stdout }} {{ sebar_release_path.stdout }}
