---
- name: SEBAR | RSYNC | Menggunakan default tools
  command: echo "{{ sebar_shared_path }}/.shared-copy"
  register: sebar_shared_rsync_copy_path

- name: SEBAR | RSYNC | Rsync metode yang digunakan untuk sinkronisasi data antar server.
  synchronize:
    src: "{{ sebar_deploy_from }}"
    dest: "{{ sebar_shared_rsync_copy_path.stdout }}"
    set_remote_user: "{{ sebar_rsync_set_remote_user }}"
    recursive: yes
    delete: yes
    archive: yes
    compress: yes
    use_ssh_args: "{{ sebar_rsync_use_ssh_args | default(omit) }}"
    rsync_opts: "{{ sebar_rsync_extra_params | default(omit) }}"
    rsync_path: "{{ sebar_rsync_path | default(omit) }}"

- name: SEBAR | RSYNC | Menerapkan kode yang dibuat ke server
  command: cp -a {{ sebar_shared_rsync_copy_path.stdout }} {{ sebar_release_path.stdout }}
