---
- name: SEBAR | S3 | Create release folder
  file:
    state: directory
    path: "{{ sebar_release_path.stdout }}"

- name: SEBAR | S3 | Get object from S3
  s3:
    bucket: "{{ sebar_s3_bucket }}"
    object: "{{ sebar_s3_object }}"
    dest: "{{ sebar_release_path.stdout }}/{{ sebar_s3_object | basename }}"
    mode: get
    region: "{{ sebar_s3_region }}"
    aws_access_key: "{{ sebar_s3_aws_access_key | default(omit) }}"
    aws_secret_key: "{{ sebar_s3_aws_secret_key | default(omit) }}"
    ignore_nonexistent_bucket: "{{ sebar_s3_ignore_nonexistent_bucket | default(omit) }}"
  when: not sebar_s3_rgw

- name: SEBAR | S3 | Get object from Ceph RGW
  s3:
    rgw: true
    s3_url: "{{ sebar_s3_url }}"
    encrypt: "{{ sebar_s3_encrypt | default(false) }}"
    bucket: "{{ sebar_s3_bucket }}"
    object: "{{ sebar_s3_object }}"
    dest: "{{ sebar_release_path.stdout }}/{{ sebar_s3_object | basename }}"
    mode: get
    aws_access_key: "{{ sebar_s3_aws_access_key | default(omit) }}"
    aws_secret_key: "{{ sebar_s3_aws_secret_key | default(omit) }}"
    ignore_nonexistent_bucket: "{{ sebar_s3_ignore_nonexistent_bucket | default(omit) }}"
  when: sebar_s3_rgw
